import { MigrationInterface, QueryRunner } from "typeorm";

export class InitMigration1756905363283 implements MigrationInterface {
    name = 'InitMigration1756905363283'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "entretiens" ("id" SERIAL NOT NULL, "date_revision" TIMESTAMP WITH TIME ZONE NOT NULL, "description" text NOT NULL, "kilometrage" integer, "realisé_par" character varying(100), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "camionId" integer, CONSTRAINT "PK_69cba477f47c995895ca456e864" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pannes_statut_enum" AS ENUM('déclarée', 'en_cours', 'reparée')`);
        await queryRunner.query(`CREATE TABLE "pannes" ("id" SERIAL NOT NULL, "date_panne" TIMESTAMP WITH TIME ZONE NOT NULL, "description" text NOT NULL, "statut" "public"."pannes_statut_enum" NOT NULL DEFAULT 'déclarée', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "camionId" integer, CONSTRAINT "PK_a4fac366d99dff9769cd9eabac5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "emplacements" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "adresse" text, "ville" character varying, "code_postal" character varying(20), CONSTRAINT "PK_1148c6cc0f5ed02e241d1499af3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "camionEmplacements" ("id" SERIAL NOT NULL, "date_assignation" TIMESTAMP NOT NULL DEFAULT now(), "camionId" integer, "emplacementId" integer, CONSTRAINT "PK_2629a37e8528cc870daad5b864e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."camions_statut_enum" AS ENUM('disponible', 'en_reparation', 'en_mission', 'hors_service')`);
        await queryRunner.query(`CREATE TABLE "camions" ("id" SERIAL NOT NULL, "immatriculation" character varying NOT NULL, "date_achat" TIMESTAMP WITH TIME ZONE NOT NULL, "kilometrage" integer NOT NULL, "statut" "public"."camions_statut_enum" NOT NULL DEFAULT 'disponible', "franchiseId" uuid, CONSTRAINT "REL_ff57c114244fbb2d4f7f1f2202" UNIQUE ("franchiseId"), CONSTRAINT "PK_175dde1f2820b683f62844a6dff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categoryProduct" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, CONSTRAINT "PK_8b34802498b52f5591b2ce2f3bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "entrepots" ("id" SERIAL NOT NULL, "nom" character varying NOT NULL, "adresse" character varying NOT NULL, "ville" character varying NOT NULL, "code_postal" character varying NOT NULL, CONSTRAINT "PK_a63ccce075c13782259b93ecfff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."commandes_stocks_statut_enum" AS ENUM('en_cours', 'soumise', 'valide', 'expediee', 'livree', 'annulee')`);
        await queryRunner.query(`CREATE TABLE "commandes_stocks" ("id" SERIAL NOT NULL, "id_formatted" character varying NOT NULL, "date_commande" TIMESTAMP NOT NULL DEFAULT now(), "date_reception" TIMESTAMP, "statut" "public"."commandes_stocks_statut_enum" NOT NULL DEFAULT 'en_cours', "montant_total" numeric(10,2), "franchiseId" uuid, "entrepotId" integer, CONSTRAINT "PK_75e1e8e08aebd5194b3f85de8b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commande_stock_produits" ("id" SERIAL NOT NULL, "id_formatted" character varying NOT NULL, "quantite" integer NOT NULL, "prix_unitaire" numeric(10,2) NOT NULL, "commandeId" integer, "produitId" uuid, CONSTRAINT "PK_f05ebe21ea984e503caedc1645f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "produits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nom" character varying NOT NULL, "description" character varying NOT NULL, "prix" numeric(10,2) NOT NULL, "seuil" integer, "actif" boolean NOT NULL DEFAULT true, "categoryId" integer NOT NULL, CONSTRAINT "PK_738095029a8d184b11939537702" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stocks" ("id" SERIAL NOT NULL, "quantite" integer NOT NULL DEFAULT '0', "franchiseeId" uuid, "produitId" uuid, CONSTRAINT "UQ_0fd77dcea81d4a26d950205da55" UNIQUE ("franchiseeId", "produitId"), CONSTRAINT "PK_b5b1ee4ac914767229337974575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu_ligne" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantite" integer NOT NULL, "menuId" uuid NOT NULL, "produitId" uuid NOT NULL, CONSTRAINT "PK_1f0b02876f77676868ddfd024c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "menu" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nom" character varying(200) NOT NULL, "description" text, "prix" numeric(10,2) NOT NULL, "actif" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "franchiseId" uuid NOT NULL, CONSTRAINT "PK_35b2a8f47d153ff7a41860cceeb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cartesFidelite" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "points" integer NOT NULL DEFAULT '0', "clientId" uuid NOT NULL, "franchiseId" uuid NOT NULL, CONSTRAINT "UQ_875999f66cc48ec9662db36dba7" UNIQUE ("clientId", "franchiseId"), CONSTRAINT "PK_3ef688356310792fa2108811612" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nom" character varying NOT NULL, "email" character varying NOT NULL, "telephone" character varying(20), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b48860677afe62cd96e12659482" UNIQUE ("email"), CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commandeClientProduits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantite" integer NOT NULL, "prixUnitaire" numeric(10,2) NOT NULL, "commandeClientId" uuid NOT NULL, "produitId" uuid NOT NULL, CONSTRAINT "UQ_de57188a4c221a6ed87d3ed89ee" UNIQUE ("commandeClientId", "produitId"), CONSTRAINT "PK_12ef07e537aca4520c200d30304" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "commande_client_menu" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantite" integer NOT NULL, "prixUnitaire" numeric(10,2) NOT NULL, "commandeClientId" uuid NOT NULL, "menuId" uuid NOT NULL, CONSTRAINT "PK_2122e16630776b5cfba66851889" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."commandeClients_statut_enum" AS ENUM('en_attente', 'payee', 'livree', 'annulee')`);
        await queryRunner.query(`CREATE TABLE "commandeClients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "utiliserPointsFidelite" boolean NOT NULL DEFAULT false, "dateCommande" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "statut" "public"."commandeClients_statut_enum" NOT NULL DEFAULT 'en_attente', "montantTotal" numeric(10,2) NOT NULL, "clientId" uuid, "franchiseId" uuid NOT NULL, CONSTRAINT "PK_6c0b3d98dd95631795093fbf963" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ventes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "id_formatted" character varying, "montant" numeric(10,2) NOT NULL, "dateVente" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "remise_fidelite" numeric(10,2) NOT NULL DEFAULT '0', "commandeClientId" uuid NOT NULL, "franchiseId" uuid NOT NULL, CONSTRAINT "PK_f2ab45fd7d5872486d54499501d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "franchises" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "nom" character varying NOT NULL, "adresse" character varying NOT NULL, "siret" character varying NOT NULL, "ville" character varying NOT NULL, "code_postal" integer NOT NULL, "statut" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8f19bb4eb53a7c5ed7f0e1151e3" UNIQUE ("siret"), CONSTRAINT "PK_5ff74e1ad0637c499c4ed139e2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tokens" ("id" SERIAL NOT NULL, "token" character varying NOT NULL, "userId" uuid, CONSTRAINT "PK_3001e89ada36263dabf1fb6210a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying, "avatar" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "roleId" integer NOT NULL, "franchiseId" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "evenements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "titre" character varying NOT NULL, "description" text, "date_debut" TIMESTAMP WITH TIME ZONE NOT NULL, "date_fin" TIMESTAMP WITH TIME ZONE, "franchise_id" uuid NOT NULL, CONSTRAINT "PK_4d738e7c6ea49548ffbdbee5cdf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "article_prix_franchise" ("id" SERIAL NOT NULL, "actif" boolean NOT NULL DEFAULT true, "prix_vente" numeric(10,2), "franchise_id" uuid NOT NULL, "produit_id" uuid NOT NULL, CONSTRAINT "UQ_8710985ffd0eade4d2c4dc478be" UNIQUE ("franchise_id", "produit_id"), CONSTRAINT "PK_a9ab0715a85d9f3114f3cb41e09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "entretiens" ADD CONSTRAINT "FK_1165105d4d396a097820457cf13" FOREIGN KEY ("camionId") REFERENCES "camions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pannes" ADD CONSTRAINT "FK_f97fba00826a388244c886fcc81" FOREIGN KEY ("camionId") REFERENCES "camions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camionEmplacements" ADD CONSTRAINT "FK_391b58db8fd93724e93b3106719" FOREIGN KEY ("camionId") REFERENCES "camions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camionEmplacements" ADD CONSTRAINT "FK_ed29c0fb25eb548416983bd4450" FOREIGN KEY ("emplacementId") REFERENCES "emplacements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "camions" ADD CONSTRAINT "FK_ff57c114244fbb2d4f7f1f22026" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commandes_stocks" ADD CONSTRAINT "FK_92acbe707be6d8f12bdf7627e01" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commandes_stocks" ADD CONSTRAINT "FK_a2065e52a255c011fdd737657b1" FOREIGN KEY ("entrepotId") REFERENCES "entrepots"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commande_stock_produits" ADD CONSTRAINT "FK_7b6ad5ea6ad50caa51938825c37" FOREIGN KEY ("commandeId") REFERENCES "commandes_stocks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commande_stock_produits" ADD CONSTRAINT "FK_b04bb5c501b0cabbdde1ae15475" FOREIGN KEY ("produitId") REFERENCES "produits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "produits" ADD CONSTRAINT "FK_7776c3f055f4e4ac0bd90e4435a" FOREIGN KEY ("categoryId") REFERENCES "categoryProduct"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_8d52e7b3f5a637373035a72b8ff" FOREIGN KEY ("franchiseeId") REFERENCES "franchises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stocks" ADD CONSTRAINT "FK_51b1cf3dcd0394e1b586660177a" FOREIGN KEY ("produitId") REFERENCES "produits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_ligne" ADD CONSTRAINT "FK_26a58597601fb8ccb9c87b4c858" FOREIGN KEY ("menuId") REFERENCES "menu"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu_ligne" ADD CONSTRAINT "FK_18ca1bc8801acd8f5e70fbd13c3" FOREIGN KEY ("produitId") REFERENCES "produits"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "menu" ADD CONSTRAINT "FK_a209aafa16baa232538f921c299" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartesFidelite" ADD CONSTRAINT "FK_8482a79d1ec3b84bad51d17ac9e" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cartesFidelite" ADD CONSTRAINT "FK_24d22dc2a679da3cf75c81949f2" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commandeClientProduits" ADD CONSTRAINT "FK_f21f3a370887e2f43a63c446c0e" FOREIGN KEY ("commandeClientId") REFERENCES "commandeClients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commandeClientProduits" ADD CONSTRAINT "FK_7712cc286cbc2365c9e58358aa1" FOREIGN KEY ("produitId") REFERENCES "produits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commande_client_menu" ADD CONSTRAINT "FK_f9067f2e7828764d364197bdd67" FOREIGN KEY ("commandeClientId") REFERENCES "commandeClients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commande_client_menu" ADD CONSTRAINT "FK_f40168107768f75fdee8ca52dbe" FOREIGN KEY ("menuId") REFERENCES "menu"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commandeClients" ADD CONSTRAINT "FK_728cf7a8a5e6e62b10360567140" FOREIGN KEY ("clientId") REFERENCES "clients"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "commandeClients" ADD CONSTRAINT "FK_353384023a260879fff74e8e969" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventes" ADD CONSTRAINT "FK_ffddd5090b6b9e8e3d48bc759cd" FOREIGN KEY ("commandeClientId") REFERENCES "commandeClients"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventes" ADD CONSTRAINT "FK_885ed985a74973159aeb120cfca" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tokens" ADD CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_48dc3a661cb2dea406ff008acc9" FOREIGN KEY ("franchiseId") REFERENCES "franchises"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evenements" ADD CONSTRAINT "FK_cff7538a8ca1a93c1b6a3672f69" FOREIGN KEY ("franchise_id") REFERENCES "franchises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_prix_franchise" ADD CONSTRAINT "FK_d3ca520242658f90e63b1852d7f" FOREIGN KEY ("franchise_id") REFERENCES "franchises"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "article_prix_franchise" ADD CONSTRAINT "FK_038057a26603ae2e18837b3d667" FOREIGN KEY ("produit_id") REFERENCES "produits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "article_prix_franchise" DROP CONSTRAINT "FK_038057a26603ae2e18837b3d667"`);
        await queryRunner.query(`ALTER TABLE "article_prix_franchise" DROP CONSTRAINT "FK_d3ca520242658f90e63b1852d7f"`);
        await queryRunner.query(`ALTER TABLE "evenements" DROP CONSTRAINT "FK_cff7538a8ca1a93c1b6a3672f69"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_48dc3a661cb2dea406ff008acc9"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "tokens" DROP CONSTRAINT "FK_d417e5d35f2434afc4bd48cb4d2"`);
        await queryRunner.query(`ALTER TABLE "ventes" DROP CONSTRAINT "FK_885ed985a74973159aeb120cfca"`);
        await queryRunner.query(`ALTER TABLE "ventes" DROP CONSTRAINT "FK_ffddd5090b6b9e8e3d48bc759cd"`);
        await queryRunner.query(`ALTER TABLE "commandeClients" DROP CONSTRAINT "FK_353384023a260879fff74e8e969"`);
        await queryRunner.query(`ALTER TABLE "commandeClients" DROP CONSTRAINT "FK_728cf7a8a5e6e62b10360567140"`);
        await queryRunner.query(`ALTER TABLE "commande_client_menu" DROP CONSTRAINT "FK_f40168107768f75fdee8ca52dbe"`);
        await queryRunner.query(`ALTER TABLE "commande_client_menu" DROP CONSTRAINT "FK_f9067f2e7828764d364197bdd67"`);
        await queryRunner.query(`ALTER TABLE "commandeClientProduits" DROP CONSTRAINT "FK_7712cc286cbc2365c9e58358aa1"`);
        await queryRunner.query(`ALTER TABLE "commandeClientProduits" DROP CONSTRAINT "FK_f21f3a370887e2f43a63c446c0e"`);
        await queryRunner.query(`ALTER TABLE "cartesFidelite" DROP CONSTRAINT "FK_24d22dc2a679da3cf75c81949f2"`);
        await queryRunner.query(`ALTER TABLE "cartesFidelite" DROP CONSTRAINT "FK_8482a79d1ec3b84bad51d17ac9e"`);
        await queryRunner.query(`ALTER TABLE "menu" DROP CONSTRAINT "FK_a209aafa16baa232538f921c299"`);
        await queryRunner.query(`ALTER TABLE "menu_ligne" DROP CONSTRAINT "FK_18ca1bc8801acd8f5e70fbd13c3"`);
        await queryRunner.query(`ALTER TABLE "menu_ligne" DROP CONSTRAINT "FK_26a58597601fb8ccb9c87b4c858"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_51b1cf3dcd0394e1b586660177a"`);
        await queryRunner.query(`ALTER TABLE "stocks" DROP CONSTRAINT "FK_8d52e7b3f5a637373035a72b8ff"`);
        await queryRunner.query(`ALTER TABLE "produits" DROP CONSTRAINT "FK_7776c3f055f4e4ac0bd90e4435a"`);
        await queryRunner.query(`ALTER TABLE "commande_stock_produits" DROP CONSTRAINT "FK_b04bb5c501b0cabbdde1ae15475"`);
        await queryRunner.query(`ALTER TABLE "commande_stock_produits" DROP CONSTRAINT "FK_7b6ad5ea6ad50caa51938825c37"`);
        await queryRunner.query(`ALTER TABLE "commandes_stocks" DROP CONSTRAINT "FK_a2065e52a255c011fdd737657b1"`);
        await queryRunner.query(`ALTER TABLE "commandes_stocks" DROP CONSTRAINT "FK_92acbe707be6d8f12bdf7627e01"`);
        await queryRunner.query(`ALTER TABLE "camions" DROP CONSTRAINT "FK_ff57c114244fbb2d4f7f1f22026"`);
        await queryRunner.query(`ALTER TABLE "camionEmplacements" DROP CONSTRAINT "FK_ed29c0fb25eb548416983bd4450"`);
        await queryRunner.query(`ALTER TABLE "camionEmplacements" DROP CONSTRAINT "FK_391b58db8fd93724e93b3106719"`);
        await queryRunner.query(`ALTER TABLE "pannes" DROP CONSTRAINT "FK_f97fba00826a388244c886fcc81"`);
        await queryRunner.query(`ALTER TABLE "entretiens" DROP CONSTRAINT "FK_1165105d4d396a097820457cf13"`);
        await queryRunner.query(`DROP TABLE "article_prix_franchise"`);
        await queryRunner.query(`DROP TABLE "evenements"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "tokens"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "franchises"`);
        await queryRunner.query(`DROP TABLE "ventes"`);
        await queryRunner.query(`DROP TABLE "commandeClients"`);
        await queryRunner.query(`DROP TYPE "public"."commandeClients_statut_enum"`);
        await queryRunner.query(`DROP TABLE "commande_client_menu"`);
        await queryRunner.query(`DROP TABLE "commandeClientProduits"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TABLE "cartesFidelite"`);
        await queryRunner.query(`DROP TABLE "menu"`);
        await queryRunner.query(`DROP TABLE "menu_ligne"`);
        await queryRunner.query(`DROP TABLE "stocks"`);
        await queryRunner.query(`DROP TABLE "produits"`);
        await queryRunner.query(`DROP TABLE "commande_stock_produits"`);
        await queryRunner.query(`DROP TABLE "commandes_stocks"`);
        await queryRunner.query(`DROP TYPE "public"."commandes_stocks_statut_enum"`);
        await queryRunner.query(`DROP TABLE "entrepots"`);
        await queryRunner.query(`DROP TABLE "categoryProduct"`);
        await queryRunner.query(`DROP TABLE "camions"`);
        await queryRunner.query(`DROP TYPE "public"."camions_statut_enum"`);
        await queryRunner.query(`DROP TABLE "camionEmplacements"`);
        await queryRunner.query(`DROP TABLE "emplacements"`);
        await queryRunner.query(`DROP TABLE "pannes"`);
        await queryRunner.query(`DROP TYPE "public"."pannes_statut_enum"`);
        await queryRunner.query(`DROP TABLE "entretiens"`);
    }

}
